services:
  nestjs-api:
    build: .
    env_file: .env
    environment:
      - PORT=${API_PORT}
      - MONGO_URI=${MONGO_URI}
    networks:
      - loadbalancing
    depends_on:
      mongo:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  nginx:
    build: ./nginx
    env_file: .env
    ports:
      - "${LOAD_BALANCER_PORT}:${LOAD_BALANCER_PORT}"
    networks:
      - loadbalancing
    depends_on:
      - nestjs-api
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  mongo:
    build: ./mongo
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodata:/data/db
    networks:
      - loadbalancing
    healthcheck:
      test: [
        "CMD",
        "mongosh",
        "--quiet",
        "-u", "${MONGO_USERNAME}",
        "-p", "${MONGO_PASSWORD}",
        "--authenticationDatabase", "${MONGO_AUth_DATABASE}",
        "--eval", "db.runCommand({ ping: 1 })"
      ]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

volumes:
  mongodata:
    driver: local

networks:
  loadbalancing:
