version: '3'
services:
  nestjs-api:
    build: .
    env_file: .env
    environment:
      - PORT=${API_PORT}
    deploy:
      replicas: 3
    networks:
      - loadbalancing

  nginx:
    build: ./nginx
    env_file: .env
    ports:
      - "${LOAD_BALANCER_PORT}:${LOAD_BALANCER_PORT}"
    networks:
      - loadbalancing
    depends_on:
      - nestjs-api

networks:
  loadbalancing: