version: '3'
services:
  nestjs-api:
    build: .
    env_file: .env
    environment:
      - PORT=${API_PORT}
    deploy:
      replicas: 3
    networks:
      - loadbalancing

  nginx:
    build: ./nginx
    env_file: .env
    ports:
      - "${LOAD_BALANCER_PORT}:${LOAD_BALANCER_PORT}"
    networks:
      - loadbalancing
    depends_on:
      - nestjs-api

  mongo: 
    build: ./mongo
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local

networks:
  loadbalancing:
