FROM nginx:stable-alpine

ARG API_PORT=3000
ARG LOAD_BALANCER_PORT=3001

COPY nginx.conf.template /etc/nginx/conf.d/default.conf.template
RUN envsubst '${API_PORT} ${LOAD_BALANCER_PORT}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf

EXPOSE ${LOAD_BALANCER_PORT}

CMD ["nginx", "-g", "daemon off;"]
